version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing NPM dependencies from package-lock.json...
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - npm run build